import 'package:flutter/material.dart';
import 'package:music_royalty/models/websitesRegistrationfields.dart';

class WebsitesFieldsConstants {
  static final List<WebsitesRegistrationFields> autofilllist =
      <WebsitesRegistrationFields>[
    WebsitesRegistrationFields(
        musictitle: "",
        stepid: "2",
        url: {
          'home': 'https://eservice.eco.loc.gov/eService_enu?SWECmd=Start',
          'registre':
              'https://eservice.eco.loc.gov/siebel/app/eservice/enu?SWECmd=GotoView&SWEView=VBC+User+Registration+Initial+Form+View&SWERF=1&SWEHo=&SWEBU=1&SWEApplet0=VBC+User+Registration+Initial+Form+Applet&SWERowId0=VRId-0',
          'form':
              'https://eservice.eco.loc.gov/siebel/app/eservice/enu?SWECmd=GotoView&SWEView=LC+General+Instructions+Detail+View+(eService)&SWERF=1&SWEHo=&SWEBU=1&SWEApplet0=LC+General+Instructions+Title+Detail+Applet+(eService)&SWERowId0=1-5BBXKVH'
        },
        autofill: false,
        sousstepid: "",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        stepid: "3",
        url: {
          'home': 'https://usisrc.org/',
          'registre': 'https://usisrc.org/applications/question/1',
          'form': ''
        },
        sousstepid: "",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        zipfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        autofill: false),
    WebsitesRegistrationFields(
        // id te7chi fih tetbadel ki trefreshi mesh fix
        musictitle: "",
        url: {
          'home': 'https://www.bmi.com/join',
          'registre':
              'https://join.bmi.com/?_gl=1*1sbh1vl*_ga*NjkxMjQ3OTIzLjE2NTQ2NDQxOTk.*_ga_MS9JDLD7MT*MTY2MDc3OTM2Ny44LjEuMTY2MDc4MDc5MC4wLjAuMA..#/writer',
          'form':
              'https://join.bmi.com/?_gl=1*91jhmd*_ga*NjkxMjQ3OTIzLjE2NTQ2NDQxOTk.*_ga_MS9JDLD7MT*MTY2MDk1NTk0MS4xMC4wLjE2NjA5NTU5NDIuMC4wLjA.#/publisher',
        },
        stepid: "4",
        sousstepid: "1",
        fnamefield: "personalFirstNameField-FirstName-FirstName-",
        lnamefield: "personalLastNameField-LastName-LastName-",
        fullname: "",
        middlenamefield: "personalMiddleNameField-MiddleName-MiddleName-",
        emailfield: "personalEmailField-EmailAddress-EmailAddress-",
        adressfield: "personalAddress1Field-Address-Address-",
        statefield: "",
        datefield: "",
        phonenumberfield: "personalCellField-CellPhone-CellPhone-",
        zipfield: "personalForeignZipField-ZIP-ZIP-",
        publisherfnamefield: "businessFirstName-FirstName-FirstName-",
        publisherlnamefield: "businessLastName-LastName-LastName-",
        publisherfullname: "",
        publishermiddlenamefield: "businessMiddleName-MiddleName-MiddleName-",
        publisheremailfield: "preparerEmail-EmailAddress-EmailAddress-",
        publisheradressfield:
            "businessAddress1-BusinessAddress-BusinessAddress-",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "businessPhone-BusinessPhone-BusinessPhone-",
        publisherzipfield: "businessZip-ZIP-ZIP-",
        autofill: false),
    WebsitesRegistrationFields(
        //te5dem bil buget
        musictitle: "",
        url: {
          'home': 'https://www.ascap.com/member-access#login',
          'registre': 'https://ome.ascap.com/',
          'form': 'https://ome.ascap.com/'
        },
        stepid: "4",
        sousstepid: "2",
        fnamefield: "writer_firstName",
        lnamefield: "writer_lastName",
        fullname: "",
        middlenamefield: "writer_middleName",
        emailfield: "writer_email",
        adressfield: "writer_addressLine1",
        statefield: "",
        datefield: "",
        phonenumberfield: "writer_phoneNumber",
        zipfield: "writer_zip",
        publisherfnamefield: "publisher_firstName",
        publisherlnamefield: "publisher_lastName",
        publisherfullname: "",
        publishermiddlenamefield: "publisher_middleName",
        publisheremailfield: "publisher_email",
        publisheradressfield: "publisher_addressLine1",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "publisher_phoneNumber",
        publisherzipfield: "publisher_zip",
        autofill: true),
    WebsitesRegistrationFields(
        musictitle: "",
        //not needed autofill
        url: {'home': 'https://www.sesac.com/', 'registre': '', 'form': ''},
        stepid: "4",
        sousstepid: "3",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        zipfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        autofill: false),
    WebsitesRegistrationFields(
        //payment meloul  tnajmsh tchof lform
        musictitle: "",
        url: {
          'home': 'https://distrokid.com/',
          'registre': 'https://distrokid.com/',
          'form': 'https://distrokid.com/plan/'
        },
        stepid: "5",
        sousstepid: "1",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "inputEmail",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        zipfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        autofill: true),
    WebsitesRegistrationFields(
        // page barka fiha artist name khw najmsh nchof stept lo5rin
        musictitle: "ctl00_rightColumn_txtAlbumName",
        autofill: true,
        url: {
          'home':
              'https://auth.cdbaby.com/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DAC68A4B0-552C-4576-8356-32D5D2625100%26redirect_uri%3Dhttps%253A%252F%252Fmembers.cdbaby.com%252Fsignin-oidc%26response_mode%3Dform_post%26response_type%3Dcode%2520id_token%26scope%3Dopenid%2520profile%2520email%2520cdbAPI%2520cdbAuthApi%2520cdbMembers%26state%3DOpenIdConnect.AuthenticationProperties%253Dt0vjCf6dgow4otednqX2mAYMp95fC4oaUHrtHSe_vF1cgowHab3PVlA9AaMMmnvsBhQHXZQ_m7ArKHHMdKENJv9P2CQF1MGwQlXDdAu9ebAB5YbzyHWv5q-E6daVucXAB_2ERVpcXPFWVWP-lviZjj15z0v3Z66Z9-MNpnW_AfL75oYFThCQfJXEQH_HNeIyFsIP6REqX3goZxzghBEfde0ZKlRqvf3cJ9wI1NzzMMy0SnDTYO2ktXLST8p9qMNA%26nonce%3D637953379376439264.NGIwMDQ2ODEtZjMyNi00MTJmLWIwOWEtMmYzNzdjNzU0NzA4ODcxMDRiNGMtNGNkNy00NzIzLWFmMWUtNzA1N2NkZDU1NTNi%26x-client-SKU%3DID_NET451%26x-client-ver%3D5.2.1.0',
          'registre': 'https://members.cdbaby.com/sign-up',
          'form': 'https://members.cdbaby.com/SingleSong/BasicAlbumInfo.aspx'
        },
        stepid: "5",
        sousstepid: "2",
        fnamefield: "ctl00_MainContent_txtFirstName",
        lnamefield: "ctl00_MainContent_txtLastName",
        fullname: "ctl00_rightColumn_txtArtistName",
        middlenamefield: "",
        emailfield: "ctl00_MainContent_txtEmail",
        adressfield: "ctl00_MainContent_txtAddressLine1",
        statefield: "ctl00_MainContent_txtCity",
        datefield: "",
        phonenumberfield: "ctl00_MainContent_txtPhone",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        autofill: true,
        musictitle: "edit_album_info_release",
        url: {
          'home': 'https://www.routenote.com/rn/login',
          'registre': 'https://www.routenote.com/rn/signup_page/design',
          'form': 'https://www.routenote.com/rn/create_album'
        },
        stepid: "5",
        sousstepid: "3",
        fnamefield: "signup_username",
        lnamefield: "",
        fullname: "edit_album_info_artist",
        middlenamefield: "",
        emailfield: "signup_email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "name",
        autofill: true,
        url: {
          'home':
              'https://web.tunecore.com/login?check=1&_ga=2.134243761.1943203254.1659741549-505015124.1659390732',
          'registre': 'https://web.tunecore.com/signup',
          'form': 'https://web.tunecore.com/singles/new'
        },
        stepid: "5",
        sousstepid: "4",
        fnamefield: "person_name",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "person_email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "mat-input-0",
        autofill: true,
        url: {
          'home':
              'https://dashboard.onerpm.com/login?_ga=2.29048376.501363854.1659741948-497452860.1659390773&_gac=1.126021375.1659741948.CjwKCAjw46CVBhB1EiwAgy6M4mC1vY0NLL2zbRm09Jjr95tqdcQQZfZbe4DGiU-RTeZdwOigmTjSDxoCdAEQAvD_BwE&_gl=1*1b2z9b5*_ga*NDk3NDUyODYwLjE2NTkzOTA3NzM.*_ga_VNEZY70FBD*MTY1OTc0MTk0OC4zLjAuMTY1OTc0MTk0OC42MA..',
          'registre': 'https://dashboard.onerpm.com/registration',
          'form':
              'https://dashboard.onerpm.com/distribution-tools/my-catalog/upload-music'
        },
        stepid: "5",
        sousstepid: "5",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "mat-input-7",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "release_name",
        autofill: true,
        url: {
          'home': 'https://artist.amuse.io/#/login',
          'registre': 'https://artist.amuse.io/#/',
          'form': 'https://artist.amuse.io/#/releases/1/'
        },
        stepid: "5",
        sousstepid: "6",
        fnamefield: "signup_form_name_field",
        lnamefield: "signup_form_lastname_field",
        fullname: "",
        middlenamefield: "",
        emailfield: "signup_page_email_field",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "signup_form_phone_field",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "releaseTitle",
        autofill: true,
        url: {
          'home': 'https://dittomusic.com/en/login/',
          'registre': 'https://dittomusic.com/en/signup/',
          'form':
              'https://dashboard.dittomusic.com/releases/2009899/music/builder/1#'
        },
        stepid: "5",
        sousstepid: "7",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "fc-EmailAddress",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.recordunion.com/login',
          'registre': 'https://www.recordunion.com/signup',
          'form':
              'https://app.recordunion.com/SubmitContent/EditReleaseInformation'
        },
        stepid: "5",
        sousstepid: "8",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "signup-email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        autofill: true,
        musictitle: "",
        url: {
          'home': 'https://auth.kobaltmusic.com/',
          'registre': '',
          'form': 'https://apply.awal.com/submit-form/'
        },
        stepid: "5",
        sousstepid: "9",
        fnamefield: "first_name",
        lnamefield: "last_name",
        fullname: "spotifyInput",
        middlenamefield: "",
        emailfield: "email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://unitedmasters.com/login',
          'registre': 'https://unitedmasters.com/join',
          'form': ''
        },
        stepid: "5",
        sousstepid: "10",
        fnamefield: "",
        lnamefield: "",
        fullname: "signup-first-last-name",
        middlenamefield: "",
        emailfield: "signup-email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://levelmusic.com/?login=login',
          'registre': 'https://levelmusic.com/?login=register',
          'form': ''
        },
        stepid: "5",
        sousstepid: "11",
        fnamefield: "mat-input-2",
        lnamefield: "mat-input-3",
        fullname: "",
        middlenamefield: "",
        emailfield: "mat-input-4",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://sxdirect.soundexchange.com/login/',
          'registre': 'https://sxdirect.soundexchange.com/join/',
          'form': ''
        },
        stepid: "6",
        sousstepid: "",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "id_email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: false,
        url: {
          'home': 'https://portal.themlc.com/login',
          'registre': 'https://portal.themlc.com/sign-up',
          'form': 'https://portal.themlc.com/profile/#user'
        },
        stepid: "7",
        sousstepid: "1",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.musicreports.com/newlogin/',
          'registre': 'https://www.musicreports.com/signup.php?rt=c6',
          'form': ''
        },
        stepid: "7",
        sousstepid: "2",
        fnamefield: "contact_name",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "contact_email",
        adressfield: "company_address",
        statefield: "company_state",
        datefield: "",
        phonenumberfield: "contact_phone",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: "company_zip"),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://portal.harryfox.com/auth/login/?return=%2F',
          'registre': 'https://www.harryfox.com/hfa-account/register',
          'form': ''
        },
        stepid: "7",
        sousstepid: "3",
        fnamefield: "firstname",
        lnamefield: "lastname",
        fullname: "business_title",
        middlenamefield: "",
        emailfield: "email_address",
        adressfield: "address_line_1",
        statefield: "city",
        datefield: "",
        phonenumberfield: "primary_phone",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: "zip_code"),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.musixmatch.com/sign-in',
          'registre': 'https://www.musixmatch.com/sign-up',
          'form':
              'https://account.musixmatch.com/?app_id=musixmatch-publishers-v2.0&origin=aHR0cHM6Ly9wdWJsaXNoZXJzLm11c2l4bWF0Y2guY29tL3NlYXJjaA&usertoken=2208239d08f3adfe7e59aafbb085f47e4d85fc99d09f4ca2826ec3'
        },
        stepid: "8",
        sousstepid: "",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.taxi.com/login',
          'registre': 'https://www.taxi.com/join',
          'form': ''
        },
        stepid: "9",
        sousstepid: "1",
        fnamefield: "hosting_user_subscriber_attributes_first_name",
        lnamefield: "hosting_user_subscriber_attributes_last_name",
        fullname: "",
        middlenamefield: "",
        emailfield: "hosting_user_login",
        adressfield: "",
        statefield: "artist_state",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://artlist.io/Home/Application/',
          'registre': '',
          'form': ''
        },
        stepid: "9",
        sousstepid: "2",
        fnamefield: "user_login",
        lnamefield: "",
        fullname: "fullname",
        middlenamefield: "",
        emailfield: "email",
        adressfield: "",
        statefield: "country",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: false,
        url: {
          'home': 'https://app.soundstripe.com/sign_in',
          'registre': 'https://app.soundstripe.com/sign_in',
          'form': ''
        },
        stepid: "9",
        sousstepid: "3",
        fnamefield: "",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.audionetwork.com/login',
          'registre': 'https://www.audionetwork.com/registration',
          'form': ''
        },
        stepid: "9",
        sousstepid: "4",
        fnamefield: "FirstName",
        lnamefield: "LastName",
        fullname: "",
        middlenamefield: "",
        emailfield: "EmailAddress",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.broadjam.com/index.php',
          'registre': 'https://www.broadjam.com/signup/broadjam/signup.php',
          'form': ''
        },
        stepid: "9",
        sousstepid: "5",
        fnamefield: "c26",
        lnamefield: "c27",
        fullname: "",
        middlenamefield: "",
        emailfield: "c23",
        adressfield: "",
        statefield: "txtCity",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: "txtPostalCode"),
    WebsitesRegistrationFields(
        musictitle: "",
        autofill: true,
        url: {
          'home': 'https://www.musicxray.com/user_session/new',
          'registre': 'https://www.musicxray.com/signup',
          'form': ''
        },
        stepid: "9",
        sousstepid: "6",
        fnamefield: "user_login",
        lnamefield: "",
        fullname: "",
        middlenamefield: "",
        emailfield: "user_email",
        adressfield: "",
        statefield: "",
        datefield: "",
        phonenumberfield: "",
        publisherfnamefield: "",
        publisherlnamefield: "",
        publisherfullname: "",
        publishermiddlenamefield: "",
        publisheremailfield: "",
        publisheradressfield: "",
        publisherstatefield: "",
        publisherdatefield: "",
        publisherphonenumberfield: "",
        publisherzipfield: "",
        zipfield: ""),
  ];
}
